### ISSUE TITLE
Page for environment variables

### ISSUE THREAD

**Issue by viperML** [hyprwm/hyprland-wiki#1]
It would be nice to have a page for what environment variables to use. Right now, the nvidia page has some:<https://github.com/hyprwm/hyprland-wiki/blob/e32263da788af80acb43cb7ba1d6b5dcb188899c/pages/Nvidia/_index.md?plain=1#L26-L36>

...but not all of these env variables are related to nvidia.

**Comment by NotAShelf** [comment]
Maybe some of those could be moved to the example wrapper section, as the NVIDIA article already links back to it. Potentially, a "final result" example (w/ both NVIDIA and other misc envvars in it) can be attached at the end of the relevant NVIDIA section.
