### ISSUE TITLE
Add installation instructions for Ubuntu

### ISSUE THREAD

**Issue by MaximilianLloyd** [hyprwm/hyprland-wiki#109]
Provide an easily installable list of the needed dependencies for Ubuntu.

**Comment by vaxerski** [comment]
no lol

**Comment by MaximilianLloyd** [comment]
Sure, that's what i'm trying to do. But to build from source you need some deps. You don't think it's worth to add that to the page to get more users?

**Comment by vaxerski** [comment]
nope, as getting it to run on ubuntu is such a pain I doubt many would want to.
