### ISSUE TITLE
Can not launch when using KMS Console

### ISSUE THREAD

**Issue by bcr-ch** [hyprwm/hyprland-wiki#111]
I have been using [KMS](https://wiki.archlinux.org/title/KMSCON) console on my laptop lately as a replacement for the standard console.

When I start Hyperland it fails with the following error

[libseat] [libseat/backend/seatd.c:64] Could not connect to socket /run/seatd.sock: No such file or directory
[libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
[libseat] [libseat/libseat.c:73] Seat opened with backend 'logind'
[backend/session/session.c:109] Successfully loaded libseat session
[libseat] [libseat/backend/logind.c:137] Could not take device: Device or resource busy
[backend/session/session.c:32] Failed to open device: '/dev/dri/card0': Resource temporarily unavailable
[backend/backend.c:210] Found 0 GPUs, cannot create backend
[backend/backend.c:385] Failed to open any DRM device
m_sWLRBackent was NULL!
terminate called after throwing an instance of 'std::runtime_error'
  what(): wlr_backend_autocreate() failed!
[1] 2744 IOT instruction (core dumped) Hyprland

coredumpctl info 2744 gives me this:
```
           PID: 2744 (Hyprland)
           UID: 1000 (bcr)
           GID: 1000 (bcr)
        Signal: 6 (ABRT)
     Timestamp: Fri 2023-02-03 10:47:01 CET (8min ago)
  Command Line: Hyprland
    Executable: /usr/bin/Hyprland
 Control Group: /user.slice/user-1000.slice/session-4.scope
          Unit: session-4.scope
         Slice: user-1000.slice
       Session: 4
     Owner UID: 1000 (bcr)
       Boot ID: 972eeb754f304cc3b56a32c1f73560f9
    Machine ID: 14c97f09963b404c89d32e0d96c32355
      Hostname: carbon
       Storage: /var/lib/systemd/coredump/core.Hyprland.1000.972eeb754f304cc3b56a32c1f73560f9.2744.1675417621000000.zst (present)
  Size on Disk: 296.3K
       Message: Process 2744 (Hyprland) of user 1000 dumped core.
                
                Stack trace of thread 2744:
                #0  0x00007f9e9917d64c n/a (libc.so.6 + 0x8864c)
                #1  0x00007f9e9912d938 raise (libc.so.6 + 0x38938)
                #2  0x00007f9e9911753d abort (libc.so.6 + 0x2253d)
                #3  0x00007f9e9947e833 _ZN9__gnu_cxx27__verbose_terminate_handlerEv (libstdc++.so.6 + 0x9a833)
                #4  0x00007f9e9948accc _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xa6ccc)
                #5  0x00007f9e9948ad39 _ZSt9terminatev (libstdc++.so.6 + 0xa6d39)
                #6  0x00007f9e9948af9d __cxa_throw (libstdc++.so.6 + 0xa6f9d)
                #7  0x000056421abdce68 n/a (Hyprland + 0x16e68)
                #8  0x000056421abfb853 n/a (Hyprland + 0x35853)
                #9  0x00007f9e99118290 n/a (libc.so.6 + 0x23290)
                #10 0x00007f9e9911834a __libc_start_main (libc.so.6 + 0x2334a)
                #11 0x000056421ac04955 n/a (Hyprland + 0x3e955)
                ELF object binary architecture: AMD x86-64
```

When using the built in tty it launches without problem

**Comment by vaxerski** [comment]
problem with your system and not hyprland. If anything, it's wlroots that fails to open a backend, not hyprland.

**Comment by bcr-ch** [comment]
FYI for others who come across the same issue... it appears to be something in KMS based on info from the [wlroots project.](https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3401)
