### ISSUE TITLE
Adding a section for clipboard managers in the wiki "Useful Utilities"

### ISSUE THREAD

**Issue by WasteOfO2** [hyprwm/hyprland-wiki#119]
Title is self explanatory.

There are CM like [cliphist](https://github.com/sentriz/cliphist) (I like this one) and [clipman](https://github.com/yory8/clipman)

I may soon make PRs adding some more utilities and stuff since i can try and help with the wiki

**Comment by WasteOfO2** [comment]
I have noticed that my page hasn't shown up, is smth wrong?

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/218273171-0dcd5e6b-9ab7-476d-ad91-77af7246b637.png)

?
