### ISSUE TITLE
waybar instructions  and FreeBSD

### ISSUE THREAD

**Issue by DiedByDisgust** [hyprwm/hyprland-wiki#127]
the "sed" line instruction is incompatible with freebsd's sed

**Comment by WasteOfO2** [comment]
can you give us a link to the wiki where it is referenced?

**Comment by DiedByDisgust** [comment]
Of course

https://wiki.hyprland.org/Useful-Utilities/Status-Bars/

Compiling manually section first line of the code box

`sed -i 's/zext_workspace_handle_v1_activate(workspace_handle_);/const std::string command = "hyprctl dispatch workspace " + name_;\n\tsystem(command.c_str());/g' src/modules/wlr/workspace_manager.cpp`

**Comment by DiedByDisgust** [comment]
> can you give us a link to the wiki where it is referenced?

Or did you mean a reference to accurate syntax of freebsd's sed?

**Comment by WasteOfO2** [comment]
nah i was asking for the wiki page

**Comment by WasteOfO2** [comment]
just to make sure, have u tried installing it from the repos? i could see a package in FreeBSD Ports

https://cgit.freebsd.org/ports/tree/x11/waybar

and then u can try and follow the instructions abt workspace modules and configs. sorry i dont use FreeBSD but i can help the best where i can
