### ISSUE TITLE
Wrong Default Value in the WiKi Page in the Master_Layout Section.

### ISSUE THREAD

**Issue by vimyumy** [hyprwm/hyprland-wiki#139]
![image](https://user-images.githubusercontent.com/118786149/221440347-2367f850-e4ec-4b36-a8ae-4073416a3dab.png)

The Default new_on_master is true NOT false,

**Comment by vaxerski** [comment]
but...
![image](https://user-images.githubusercontent.com/43317083/221443102-4a9968f9-e50f-4a4a-8642-199de2e28384.png)

![image](https://user-images.githubusercontent.com/43317083/221443106-db86b8f5-506a-4ea4-9861-6f33a535033d.png)
