### ISSUE TITLE
Package seatd having error in installation.

### ISSUE THREAD

**Issue by adityakrcodes** [hyprwm/hyprland-wiki#143]
I was installing the buildtools for hyprland and faced the following issue.

`yay -S gdb ninja gcc cmake meson libxcb xcb-proto xcb-util xcb-util-keysyms libxfixes libx11 libxcomposite xorg-xinput libxrender pixman wayland-protocols cairo pango seatd libxkbcommon xcb-util-wm xorg-xwayland libinput
warning: gdb-12.1-2 is up to date -- reinstalling
warning: ninja-1.11.1-2 is up to date -- reinstalling
warning: gcc-12.2.1-2 is up to date -- reinstalling
warning: cmake-3.25.2-1 is up to date -- reinstalling
warning: meson-1.0.0-2 is up to date -- reinstalling
warning: libxcb-1.15-2 is up to date -- reinstalling
warning: xcb-proto-1.15.2-2 is up to date -- reinstalling
warning: xcb-util-0.4.1-1 is up to date -- reinstalling
warning: xcb-util-keysyms-0.4.1-4 is up to date -- reinstalling
warning: libxfixes-6.0.0-2 is up to date -- reinstalling
warning: libx11-1.8.4-1 is up to date -- reinstalling
warning: libxcomposite-0.4.6-1 is up to date -- reinstalling
warning: xorg-xinput-1.6.3-3 is up to date -- reinstalling
warning: libxrender-0.9.11-1 is up to date -- reinstalling
warning: pixman-0.42.2-1 is up to date -- reinstalling
warning: cairo-1.17.8-2 is up to date -- reinstalling
warning: pango-1:1.50.12-1 is up to date -- reinstalling
warning: libxkbcommon-1.5.0-1 is up to date -- reinstalling
warning: xcb-util-wm-0.4.2-1 is up to date -- reinstalling
warning: xorg-xwayland-22.1.8-1 is up to date -- reinstalling
warning: libinput-1.22.1-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (23) cairo-1.17.8-2  cmake-3.25.2-1  gcc-12.2.1-2  gdb-12.1-2  libinput-1.22.1-1  libx11-1.8.4-1  libxcb-1.15-2  libxcomposite-0.4.6-1  libxfixes-6.0.0-2  libxkbcommon-1.5.0-1  libxrender-0.9.11-1
              meson-1.0.0-2  ninja-1.11.1-2  pango-1:1.50.12-1  pixman-0.42.2-1  seatd-0.7.0-2  wayland-protocols-1.31-1  xcb-proto-1.15.2-2  xcb-util-0.4.1-1  xcb-util-keysyms-0.4.1-4  xcb-util-wm-0.4.2-1
              xorg-xinput-1.6.3-3  xorg-xwayland-22.1.8-1

Total Download Size:     0.04 MiB
Total Installed Size:  285.15 MiB
Net Upgrade Size:        0.59 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
 seatd-0.7.0-2-x86_64.pkg.tar.zst failed to download
error: failed retrieving file 'seatd-0.7.0-2-x86_64.pkg.tar.zst' from at.arch.mirror.kescher.at : The requested URL returned error: 404
error: failed retrieving file 'seatd-0.7.0-2-x86_64.pkg.tar.zst' from mirror.theo546.fr : Failed to connect to mirror.theo546.fr port 443 after 10000 ms: Timeout was reached
error: failed retrieving file 'seatd-0.7.0-2-x86_64.pkg.tar.zst' from mirror.jordanrey.me : The requested URL returned error: 404
error: failed retrieving file 'seatd-0.7.0-2-x86_64.pkg.tar.zst' from arch.kyberorg.fi : The requested URL returned error: 404
error: failed retrieving file 'seatd-0.7.0-2-x86_64.pkg.tar.zst' from archlinux.koyanet.lv : The requested URL returned error: 404
error: failed retrieving file 'seatd-0.7.0-2-x86_64.pkg.tar.zst' from pkg.fef.moe : The requested URL returned error: 404
error: failed retrieving file 'seatd-0.7.0-2-x86_64.pkg.tar.zst' from mirror.sfo12.us.leaseweb.net : The requested URL returned error: 404
error: failed retrieving file 'seatd-0.7.0-2-x86_64.pkg.tar.zst' from de.arch.mirror.kescher.at : The requested URL returned error: 404
error: failed retrieving file 'seatd-0.7.0-2-x86_64.pkg.tar.zst' from mirrors.ocf.berkeley.edu : The requested URL returned error: 404
error: failed retrieving file 'seatd-0.7.0-2-x86_64.pkg.tar.zst' from archlinux.uk.mirror.allworldit.com : Failed to connect to archlinux.uk.mirror.allworldit.com port 443 after 10001 ms: Timeout was reached
error: failed retrieving file 'seatd-0.7.0-2-x86_64.pkg.tar.zst' from archlinux.thaller.ws : The requested URL returned error: 404
error: failed retrieving file 'seatd-0.7.0-2-x86_64.pkg.tar.zst' from archmirror.it : The requested URL returned error: 404
error: failed retrieving file 'seatd-0.7.0-2-x86_64.pkg.tar.zst' from mirror.alwyzon.net : The requested URL returned error: 404
error: failed retrieving file 'seatd-0.7.0-2-x86_64.pkg.tar.zst' from archlinux.za.mirror.allworldit.com : The requested URL returned error: 404
error: failed retrieving file 'seatd-0.7.0-2-x86_64.pkg.tar.zst' from arch.hu.fo : The requested URL returned error: 404
error: failed retrieving file 'seatd-0.7.0-2-x86_64.pkg.tar.zst' from mirror.cj2.nl : The requested URL returned error: 404
error: failed retrieving file 'seatd-0.7.0-2-x86_64.pkg.tar.zst' from arch.yhtez.xyz : The requested URL returned error: 404
error: failed retrieving file 'seatd-0.7.0-2-x86_64.pkg.tar.zst' from zxcvfdsa.com : The requested URL returned error: 404
error: failed retrieving file 'seatd-0.7.0-2-x86_64.pkg.tar.zst' from mirroir.labhouse.fr : The requested URL returned error: 404
error: failed retrieving file 'seatd-0.7.0-2-x86_64.pkg.tar.zst' from mirror.fra10.de.leaseweb.net : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
 -> error installing repo packages`

**Comment by vaxerski** [comment]
"I don't know how to use Arch so I will post onto the Hyprland bug tracker!"

update your mirrors.

**Comment by adityakrcodes** [comment]
> "I don't know how to use Arch so I will post onto the Hyprland bug tracker!"

There is no issue with hyprland, the issue is with seatd package installation. I guess the mirrors are down for some reason.

Fix for Arch Users:
1. Manually download the package from the source repo of seats. ([repo link](https://git.sr.ht/~kennylevinsen/seatd))
2. Install the package with the following command
`sudo pacman -U <package-name>`
Example:
`sudo pacman -U seatd-0.7.0-3-x86_64.pkg.tar.zst`
4. Now, try installing hyprland again with your preferred AUR helper.
5. `paru -S hyprland` or if you use yay `yay -S hyprland`

**Comment by Aqa-Ib** [comment]
lol
update your Arch linux mirrors as vaxry said, that is the better solution for your problem!

**Comment by adityakrcodes** [comment]
I did update the mirrors even before posting the issue here mate.
And it didn't work as it should, so I manually installed seatd.

**Comment by vaxerski** [comment]
in any case it's not a hl issue???

**Comment by Aqa-Ib** [comment]
I recommend you to run this command:
`reflector --latest 5 --sort rate --save /etc/pacman.d/mirrorlist`
Note it will overwrite your pacman mirrorlist.
https://wiki.archlinux.org/title/Reflector
Good luck.

**Comment by adityakrcodes** [comment]
> in any case it's not a hl issue???

Nope! 
Hyprland is all good 👍🏻

**Comment by adityakrcodes** [comment]
> I recommend you to run this command: `sudo reflector --latest 5 --sort rate --save /etc/pacman.d/mirrorlist` Note it will overwrite your pacman mirrorlist. https://wiki.archlinux.org/title/Reflector Good luck.

Thanks for the help 😄 , but I already did this.

**Comment by HighSteam** [comment]
> > I recommend you to run this command: `sudo reflector --latest 5 --sort rate --save /etc/pacman.d/mirrorlist` Note it will overwrite your pacman mirrorlist. https://wiki.archlinux.org/title/Reflector Good luck.
> 
> Thanks for the help smile , but I already did this.

did u fix it man?

**Comment by adityakrcodes** [comment]
> > > I recommend you to run this command: `sudo reflector --latest 5 --sort rate --save /etc/pacman.d/mirrorlist` Note it will overwrite your pacman mirrorlist. https://wiki.archlinux.org/title/Reflector Good luck.
> > 
> > Thanks for the help smile , but I already did this.
> 
> did u fix it man?

I Installed all the dependencies manually by downloading the installation files. Then it worked that time!
