### ISSUE TITLE
Question: splitting 'slaves' horizontally ? 

### ISSUE THREAD

**Issue by fx0rec** [hyprwm/hyprland-wiki#151]
Working with my code editor I'd prefer to have it taking up half the screen, then the browser the other half, but below the browser I'd like 2-3 terminals (ultrawide monitor) stacked like a pyramid
so:

Master
mini-Master
Slave
  _______________________
|                   |                 |
|                   |                 |
|   m-M        |                 |
|                   |     M         |
|_____________                |
|  S     |   S   |                 |
|________________________
Github messed it up: https://pastebin.com/6uD61WtZ

I've set the `orientationright` but I have absolutely no idea what this kind of layout is called nor what dispatcher I'm looking for, but I'm guessing it's related to groups? Included two terminals in a group but wasn't able to place them horizontally.
Please forgive my ignorance, an answer to this would be very much appreciated!

**Comment by Aqa-Ib** [comment]
You posted the question in the wrong place.
Try asking it here: https://github.com/hyprwm/Hyprland/discussions

**Comment by fx0rec** [comment]
> You posted the question in the wrong place. Try asking it here: https://github.com/hyprwm/Hyprland/discussions

Sorry man I'm clearly not thinking straight today. Ty.
