### ISSUE TITLE
NixOS support

### ISSUE THREAD

**Issue by affieuk** [hyprwm/hyprland-wiki#154]
In the [Getting Started](https://wiki.hyprland.org/Getting-Started/Installation/) guide, it says that NixOS is very supported, however on the nix page it states "Hyprland is NOT supported on NixOS stable".

Hopefully it is supported on stable and if so which part of the docs do I follow?

**Comment by vaxerski** [comment]
@fufexan

**Comment by fufexan** [comment]
> In the [Getting Started](https://wiki.hyprland.org/Getting-Started/Installation/) guide, it says that NixOS is very supported, however on the nix page it states "Hyprland is NOT supported on NixOS stable".
> 
> Hopefully it is supported on stable and if so which part of the docs do I follow?

Stable has been known to have issues with mesa or other system components mismatches. You can try it out, but I cannot guarantee it will work.

I'm working on updating the nixpkgs Hyprland package along with all other hypr* packages, and adding the NixOS and Home Manager modules upstream. When that's done, it will work even on stable (23.05 and later).

**Comment by affieuk** [comment]
Great, I might have a mess around with it on unstable for now.
