### ISSUE TITLE
Actived clipboard item become void if I do not select anything in the rofi menu

### ISSUE THREAD

**Issue by huge-pancake** [hyprwm/hyprland-wiki#169]
I followed this page https://wiki.hyprland.org/Useful-Utilities/Clipboard-Managers/ to set up my clipboard.

Everything works right but this thing in the title:

If I don't select any item in the rofi menu and just press ESC to exit, the next time I press Ctrl+V, I get nothing (wl-copy read nothing from the menu)

Could you please add something to prevent wl-copy command if rofi command returns nothing? I relly had no idea about this.

**Comment by vaxerski** [comment]
hyprland does not manage your clipboard
