### ISSUE TITLE
Remap Caps Lock to Super

### ISSUE THREAD

**Issue by 31JSON** [hyprwm/hyprland-wiki#175]
I've seen the wiki entry on remapping Caps Lock to Ctrl, however I can't seem to figure out the syntax to get Caps Lock mapped to SUPER. Can this be added to the Wiki?

Thanks for the great documentation.

**Comment by kronikpillow** [comment]
```
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = caps:escape
    kb_rules =
}
```
