### ISSUE TITLE
Mousewheel button scrolling not working

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [hyprwm/hyprland-wiki#177]
Using the wiki, the mouse wheel button scrolling does not work (Tested on Firefox).

Steps to reproduce:
- Enable _use autoscrolling_ in Firefox
- Open the hyprland wiki
- Try to scroll

**Comment by vaxerski** [comment]
works for me...?

**Comment by fufexan** [comment]
Doesn't seem like an issue with the wiki. Closing.
