### ISSUE TITLE
200hz monitor

### ISSUE THREAD

**Issue by g0dm0d** [hyprwm/hyprland-wiki#179]
Hello, ran into an interesting problem today. Today one monitor stopped working. After fiddling with packages and their versions came to the conclusion that they are not the problem. And by gauge method I realized that the problem was the frequency of the monitor. I do not know why, but the frequency 200hz stopped working. As soon as I changed to 144hz all at once worked. Any information on this, what is it about and why it suddenly stopped working?

graphics card:
nvidia GP106 [GeForce GTX 1060 6GB]

**Comment by vaxerski** [comment]
Nvidia is not supported.

Most likely either your nvidia drivers caused an issue, or it's a problem with wlroots. Can't really think of another issue.

You can check on `sway-git` (note the -git) but I am pretty sure it will be the same.
