### ISSUE TITLE
cyclenext/swapnext are unpredictable

### ISSUE THREAD

**Issue by xdavidel** [hyprwm/hyprland-wiki#186]
I notice that if one is to use `swapnext` - the clients still preserve their order in the "stack".
This leads to `cyclenext` become unpredictable since the client order in the screed does not reflect to the order in the "stack":

```
------------- -----------
|            |     2     |
|      1     |------------
|            |     3     |
------------- -----------

------------- -----------
|            |     2     |
|      3     |------------
|            |     1     |
------------- -----------
```

Any idea on how to make this a little more predictable?
(since there is a dwindle layout and master layout to consider)

I prefer always using those instead of movefocus and movewindow.

**Comment by vaxerski** [comment]
jesus christ y'all have some real gaps in like, reading

```
bind = SUPER, X, layoutmsg, cycleprev
```
