### ISSUE TITLE
Advanced Config page is not easy to land on

### ISSUE THREAD

**Issue by mmahmoudian** [hyprwm/hyprland-wiki#190]
Through online search engine I landed on a page titled "[Advanced Config](https://wiki.hyprland.org/Configuring/Advanced-config/)". I then wondered why I've never seen this page before! The answer was pretty clear: it is not listed in the navigation sidebar (left screenshot), and it does not get listed in the search box (right screenshot).

I strongly believe that this page can make life much much easier for user who want to write their config from scratch.

 <img src="https://user-images.githubusercontent.com/390889/232075347-eba0e7b1-39ea-4c9b-8544-be8c3432943c.png" align="left" />

 <img src="https://user-images.githubusercontent.com/390889/232075654-44517786-83e3-4c3f-bd6d-7b900ce01746.png" align="right" />

**Comment by vaxerski** [comment]
it's an old page that was removed a while back and idfk why it's still there tbh

It got split into separate pages.

**Comment by mmahmoudian** [comment]
Some minutes more of diving into the wiki, it seems some of the content of that page (at least those parts that I was looking for) is now in [/Configuring/Dispatchers/](https://wiki.hyprland.org/Configuring/Dispatchers/). 

As a side comment, I think the term "Dispatchers" is very disconnected for what is presented there. I suggest renaming it to something like "Workspaces and Windows". It more resembles the actual content. Then user can see the subheading of "List of Dispatchers" in that page and get acquainted with that term.

**Comment by vaxerski** [comment]
workspaces and windows does not refer to what is on that page.
