### ISSUE TITLE
What is VFR anyway?

### ISSUE THREAD

**Issue by murlakatamenka** [hyprwm/hyprland-wiki#193]
It's just left as abbreviation but isn't mentioned elsewhere (or is it?)

https://github.com/hyprwm/hyprland-wiki/blob/0d2dee3a116c089725aaa6eb8e646a015241cb43/pages/Configuring/Variables.md?plain=1#L235

It has something to do with [damage tracking](https://emersion.fr/blog/2019/intro-to-damage-tracking/). __V__ __F__ull __R__edraw or something?

---

VRR (Variable Refresh Rate aka Adaptive Sync) is more common and thus easier to find, I knew that one.

**Comment by vaxerski** [comment]
It has nothing to do with damage tracking.

VFR: New frame is submitted to the pipeline when there is a need for one (something changed and we need to redraw)
No VFR: New frames are submitted every time your monitor has a vblank. This does not mean we redraw everything, if there's nothing to redraw, we'll submit the last drawn frame. This has a serious effect on the CPU usage, though.

**Comment by murlakatamenka** [comment]
Okay, thanks for the explanation.

Still, to which human words does it _decipher_?

**Comment by vaxerski** [comment]
varyabel fræm ræt
