### ISSUE TITLE
Wrong default value in Variables: [Empty] instead of [[Empty]]

### ISSUE THREAD

**Issue by Rdeisenroth** [hyprwm/hyprland-wiki#197]
The default value for empty strings is defined as `[[Empty]]` here:

https://github.com/hyprwm/Hyprland/blob/1a91c6ee603e3e779f288ad9189992faeda944f8/src/config/ConfigManager.hpp#L19

But the wiki says it's `[Empty]` instead, which is wrong. This can also be verified using hyprctl:
```sh
> hyprctl getoption decoration:screen_shader -j | jq '.str'
"[[EMPTY]]"
```

**Comment by vaxerski** [comment]
wasnt meant to be _literally_ what's there but more like _meaningfully_, but ok
