### ISSUE TITLE
Add "Launching methods" under each status bar tutorial

### ISSUE THREAD

**Issue by ardishco-the-great** [hyprwm/hyprland-wiki#205]
For this I will open a PR adding the launch commands for Hybrid and Waybar since It's not all that hard but I am very confused on what command to use for launching ewwbar, If anyone knows how to do that, send it under this issue or open a PR.

If you as a maintainer are reading this, please add the launch commands! It would be very helpful to anyone new to Waybar, Eww or Hybrid (more so to new eww users)

**Comment by bvr-yr** [comment]
```shell
eww daemon && eww open <your_bar_name>
``` 
or you can just `eww open`/`eww open-many`, it will start the daemon if not already running

**Comment by ardishco-the-great** [comment]
> ```shell
> eww daemon && eww open <your_bar_name>
> ```
> 
> `bar_name` is that of `defwindow <bar_name>` in your `.yuck`
> 
> or you can just `eww open`/`eww open-many`, it will start the daemon if not already running


I'm not entirely familiar with setting up eww yet. I've forked this repo and have added a few changes, would you be willing to add a few lines there that we could open a PR with?

**Comment by fufexan** [comment]
I believe this is out of scope for the wiki. Each of the listed projects already have the instructions in their READMEs.
