### ISSUE TITLE
A note about PR #226 re: waybar window title

### ISSUE THREAD

**Issue by scresante** [hyprwm/hyprland-wiki#227]
It might be wise to note that a window has to lose and gain focus before waybar will display the title. That had me screwed up for a while. https://github.com/hyprwm/hyprland-wiki/pull/226

**Comment by scresante** [comment]
I just found out that this is better documented in https://github.com/Alexays/Waybar/wiki/Module:-Hyprland
https://github.com/Alexays/Waybar/wiki/Module:-Taskbar is also a fine option for window titles.

**Comment by vaxerski** [comment]
closed cuz merged
