### ISSUE TITLE
Add hyprland-nvidia (AUR) to the wiki as an option?

### ISSUE THREAD

**Issue by System-x64** [hyprwm/hyprland-wiki#233]
Before submitting an actual PR, i just want to confirm this package actually work (I don't have any Nvidia cards) and if it does...should we add this as another option (In the Nvidia section)? Look I can't try this package, just found it out in a yt video.
https://aur.archlinux.org/packages/hyprland-nvidia
![image](https://github.com/hyprwm/hyprland-wiki/assets/90208727/93afcd9b-7c04-4794-ad63-e7caedf5eda2)

**Comment by vaxerski** [comment]
I don't know for sure either, but maaany people use it so it should work

**Comment by System-x64** [comment]
Ok
