### ISSUE TITLE
Hardware acceleration

### ISSUE THREAD

**Issue by GrabbenD** [hyprwm/hyprland-wiki#245]
Is there actually any way to verify if the desktop's animations are hardware accelerated?

For instance, with Chromium based browsers it's possible to determinate if HW acceleration is available for video encoding & decoding through `chrome://gpu` or `about:support` in Firefox.

I find this question practically interesting after discovering that hardware acceleration can be complete lost (without any indication) on NixOS when there's multiple Mesa versions present between various components (https://github.com/NixOS/nixpkgs/issues/228586#issuecomment-1527030148)

**Comment by vaxerski** [comment]
I don't think hardware rendering can be disabled without the `WLR_RENDERER_ALLOW_SOFTWARE` env var set.
