### ISSUE TITLE
dp-change everytime i restart so i try to bind workstations 1,2,3 to monitor 1 not working

### ISSUE THREAD

**Issue by andresparrab** [hyprwm/hyprland-wiki#250]
![image](https://github.com/hyprwm/hyprland-wiki/assets/60740824/cc9556eb-4397-4c46-8a88-2df32e6f365b)

# At work below
monitor=desc:BOE 0x0868, disable
monitor=desc:HP Inc. HP E243i CNK01418XX, 1920x1200@60, 0x0, 1,
monitor=desc:HP Inc. HP E243i CNK01418XX, transform,1
monitor=desc:Philips Consumer Electronics Company PHL 346P1C UK02251005830, 3440x1440@60, 1200x0, 1 

workspace=monitor:desc:HP Inc. HP E243i CNK01418X,1,rounding:false,bordersize:0
workspace=monitor:desc:HP Inc. HP E243i CNK01418X,2
workspace=monitor:desc:HP Inc. HP E243i CNK01418X,3

Every time i restart my laptop connected to my docking station i get different dp numbers like before it was dp-1 and dp-2, after restart i get dp-3 and dp-4 and so own

So i decided to use monitor:desc: to bind the workspace to the monitors but it does not work only when i use DP-numbers

How can i do to fix this problem to be able to bind the workspaces to a monitor if the dp number change?
or maybe if i can request a feature to be able to add base on monitor desc name?

thank you in advance

**Comment by skogler** [comment]
I have the same kind of problem.  The issue is that you cannot assign a custom ID or so by matching a monitor description. If that were possible you could use the assigned ID in other rules. Maybe that would be a nice feature request? 

My workaround for this is to run this bash script manually:

```bash
# puts workspaces on alternating monitors
# if you have two monitors:
#  m1: 1 3 5 7 9
#  m2: 2 4 6 8 10
# if you have three:
#  m1: 1 4 7 10
#  m2: 2 5 8
#  m3: 3 6 9
arrange_workspaces() {
    mapfile -t monitors < <( hyprctl monitors -j | jq -r '.[].name' )
    for ((ws = 1; ws <= 10; ws++)); do
        monitor="${monitors[(ws - 1) % ${#monitors[@]}]}"
        hyprctl dispatch moveworkspacetomonitor "${ws}" "${monitor}" > /dev/null
        hyprctl keyword workspace "${ws},monitor:${monitor}" > /dev/null
    done
}
```

Not really convenient, but does what I want.

**Comment by MightyPlaza** [comment]
you can now use monitor:desc: inside workspace rules on v0.27
should also be added in the wiki
