### ISSUE TITLE
Start in TTY not work.

### ISSUE THREAD

**Issue by archieve-cn** [hyprwm/hyprland-wiki#251]
My tablet not work with hyprland. it's use intel-gpu and nvidia gpu.
And Before, I have got a session backend is null. 
But it seems not work. the log I show some case:
![QQ图片20230618181941](https://github.com/hyprwm/hyprland-wiki/assets/11844458/c908637d-b9d2-4fcb-8e4b-1dd1ef900d8e)

**Comment by fufexan** [comment]
Not a wiki issue.
