### ISSUE TITLE
How to disable touchdevice

### ISSUE THREAD

**Issue by gfhdhytghd** [hyprwm/hyprland-wiki#259]
I have a screen which is touchable, but the touch sensor is broken so some time it give a wrong input, I want to disable it, I'v tried to do something like:

device:Touch Device at 556a10891160 {
enabled=no
}

but it doesn't work
I notice that in the wiki, there is a:
enabled -> (only for mice / touchpads / keyboards)
so i'd like to know how to disable it

**Comment by vaxerski** [comment]
touchdevices are not supported for disabling yet

**Comment by gfhdhytghd** [comment]
I wish this function could be add in the future, or I have to use other de/wm

**Comment by vaxerski** [comment]
technically you can blacklist the driver for it :P

**Comment by vaxerski** [comment]
closing as this is an issue in hl not wiki
