### ISSUE TITLE
Programs taking too long to launch on startup

### ISSUE THREAD

**Issue by Schwarzeisc00l** [hyprwm/hyprland-wiki#261]
I tried installing xdg-desktop-portal-hyprland both from the AUR and from the Void Repos. [(Bedrock Linux)](https://bedrocklinux.org/). It still takes too long to open. Am i missing something?

**Comment by vaxerski** [comment]
do you have xdg-desktop-portal too? check also whether xdph doesnt crash?

**Comment by Schwarzeisc00l** [comment]
Package `xdg-desktop-portal' already installed.
And it's also installed on Aur.
How can i check the logs?
