### ISSUE TITLE
Which section would multi GPU setup belong to?

### ISSUE THREAD

**Issue by WasteOfO2** [hyprwm/hyprland-wiki#263]
https://github.com/hyprwm/Hyprland/issues/2622

In the issue mentioned above, i promised i would document the results to the wiki, given how common this setup is.

In which section would this page belong to and what should i name it?

**Comment by WasteOfO2** [comment]
@vaxerski friendly ping

**Comment by ItachiSan** [comment]
Hi! Given that I was able to make my laptop work thanks to @WasteOfO2 's guide, I would love to have the guide to be easily available to everyone :smile:

**Comment by WasteOfO2** [comment]
> Hi! Given that I was able to make my laptop work thanks to @WasteOfO2 's guide, I would love to have the guide to be easily available to everyone smile

<3

**Comment by ItachiSan** [comment]
Hey @WasteOfO2 , you closed the issue but your page is still not in the sidebar tree :/

**Comment by WasteOfO2** [comment]
> Hey @WasteOfO2 , you closed the issue but your page is still not in the sidebar tree :/

Odd, will fix in a PR

**Comment by WasteOfO2** [comment]
@ItachiSan it has been fixed, closing the issue
