### ISSUE TITLE
Crash on first launch (Black screen) 

### ISSUE THREAD

**Issue by RoccoRakete** [hyprwm/hyprland-wiki#265]
When I first start hyprland, no matter if from a tty or via a loginmanager, I get a black screen until I unplug the monitor and plug it back in. This kicks me back to the tty and I can starhyprland just as usual.. 

Log: 

https://pastebin.com/rHQvy77L

**Comment by vaxerski** [comment]
wrong repo

**Comment by RoccoRakete** [comment]
ohh sorry
