### ISSUE TITLE
Low contrast in some elements makes text hard to read

### ISSUE THREAD

**Issue by HoolaBoola** [hyprwm/hyprland-wiki#28]
The current theme makes it hard to read some parts of the [wiki](https://wiki.hyprland.org/Configuring/Variables/), at least on my laptop and phone's displays. Mind you, I tend to have pretty low brightness, increasing the brightness to near 100% makes it a bit easier to read but I don't think that should be expected.

Below are a couple screenshots

![image](https://user-images.githubusercontent.com/46967490/194952218-41fa6dae-c9c7-4055-b3a6-ab02859ade1d.png)

![image](https://user-images.githubusercontent.com/46967490/194952438-2b86cb60-d9ab-494a-8ce9-39a886a18c04.png)
Dark text on dark background makes it hard to see what's in the code blocks.

If I understand correctly, the theme is set in a private backend repo which outsiders cannot see, so I hope posting this to this repo instead is ok.

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/194955904-c7edec31-24d7-4d13-8465-3668bc53bae2.png)

disable whatever  night mode plugin you have. This is not our fault.

**Comment by HoolaBoola** [comment]
I do not have any night mode plugin installed, tried with two browsers on PC and two browsers on Android and all look as it did in my picture.

Also I figured out why we see it differently. My devices use light theme. Switching my phone to dark theme changes the text colour to what your picture shows. So presumably the code blocks' font colour depends on system theme.

**Comment by vaxerski** [comment]
thats better. Thanks.

**Comment by vaxerski** [comment]
@fufexan can you look into the css I think I forced the same on all but I am unsure

**Comment by fufexan** [comment]
Yeah.

**Comment by vaxerski** [comment]
closing cuz forgor
