### ISSUE TITLE
Autostarting Apps

### ISSUE THREAD

**Issue by iynaix** [hyprwm/hyprland-wiki#281]
https://wiki.hyprland.org/FAQ/#how-do-i-autostart-my-favorite-apps

The given example seems overly complicated for what it's supposed to achieve.

Wouldn't the following be a much simpler way to achieve the same result?

```
exec-once=hyprctl dispatch exec '[workspace 1 silent] kitty'
exec-once=hyprctl dispatch exec '[workspace 2 silent] subl'
exec-once=hyprctl dispatch exec '[workspace 3 silent] mailspring'
exec-once=hyprctl dispatch exec '[workspace 4 silent] firefox'
```

**Comment by vaxerski** [comment]
`exec-once = [workspace 1 silent] kitty` is also valid...?

**Comment by iynaix** [comment]
Yep, that works as well! Used the shorter version in the PR.
