### ISSUE TITLE
Variables page has not been updated yet

### ISSUE THREAD

**Issue by stauersbol** [hyprwm/hyprland-wiki#295]
I was fixing the new blur breaking changes stuff in my config, but when I went to look at the docs for the fix it didn't seem like it had been updated?

![image](https://github.com/hyprwm/hyprland-wiki/assets/9026132/0567432f-74aa-4aab-a315-ad4a0851f44a)
This is what I currently see on https://wiki.hyprland.org/Configuring/Basic-Config/#decoration and from what I gathered the blur stuff should be its own sub category

And the new change is this: https://github.com/hyprwm/hyprland-wiki/commit/7548311bb5d03037881f89c53356ee9f31f46227

Guess it might be worth taking a look!

**Comment by vaxerski** [comment]
basic config has not existed for a year now.

**Comment by stauersbol** [comment]
Ah I figured it out
I didn't choose the correct version of the wiki, my bad.
