### ISSUE TITLE
bug in locksrcreen (skips the password)

### ISSUE THREAD

**Issue by Simao-pp-C** [hyprwm/hyprland-wiki#296]
i´m using this (https://www.youtube.com/watch?v=whAi_y_LfEE) and when i lock screen if i click (super / windosbutton) it just bypasses the password

**Comment by vaxerski** [comment]
zero information, wrong bug tracker

**Comment by Simao-pp-C** [comment]
sorry, i just realize now the bug is in swaylock .
is there a swaylock page to submit this bug?
