### ISSUE TITLE
.. was not defined in scope errors while compiling

### ISSUE THREAD

**Issue by bearcatsandor** [hyprwm/hyprland-wiki#3]
os: Gentoo Linux
kernel: 5.18.16-zen1 #2 ZEN SMP PREEMPT_DYNAMIC

Hey folks.  For about two weeks now, when attempting to install the latest hyprland from git I'm getting errors similar to 

Hyprland/src/managers/input/InputManager.cpp:735:60: error: 'wlr_keyboard_from_input_device' was not declared in this scope; did you mean 'wlr_keyboard_grab_interface'?

I'd love some help debugging this.   Thank you.

 My compile log is here:  https://gist.github.com/bearcatsandor/8769644f92b10b0f03cd00f3693c423d

**Comment by vaxerski** [comment]
hyprland bundles wlroots. Do not use the system ones.

**Comment by bearcatsandor** [comment]
First off, I meant to file this but in hyperwm/hyprland but I hit the wrong link, and didn't notice. Ill move it there if you wish.

I have removed wl-roots from my system and this error still persists. I have made sure that all packages listed as dependencies on the wiki are installed and at their latest versions.  Any other ideas? It looks like a coding error, but it's passing it's build so it's likely not.

**Comment by bearcatsandor** [comment]
I have the following Wayland related packages installed:

=app-misc/wayland-utils-1.0.0
=dev-cpp/waylandpp-1.0.0
=dev-libs/plasma-wayland-protocols-1.7.0
=dev-libs/wayland-1.21.0
=dev-libs/wayland-protocols-1.26
=dev-qt/qtwayland-5.15.5-r1
=dev-qt/qtwaylandscanner-5.15.5
=dev-util/wayland-scanner-1.21.0
=kde-frameworks/kwayland-5.97.0
=x11-base/xwayland-22.1.3

Might any of them be interfering?

**Comment by vaxerski** [comment]
you probably forgot to `git clone --recursive`.

**Comment by bearcatsandor** [comment]
A-ha!  That was it! Thank you!
