### ISSUE TITLE
Information about how to configure vrr per display missing

### ISSUE THREAD

**Issue by David-Aguilo** [hyprwm/hyprland-wiki#319]
Greetings.

I was looking through the release notes of version [v0.29.0](https://github.com/hyprwm/Hyprland/releases/tag/v0.29.0) and saw that support for variable refresh rate per display had been added, yet when I went to check how to configure the VRR per display in the wiki, I saw no mention of it neither in the Variables section, nor the Monitors section. It appears the information on how to configure this is missing.

**Comment by vaxerski** [comment]
b8de59bf08eec5f1d8103e16744b749ff4315b93
