### ISSUE TITLE
Slackbuild for this exists

### ISSUE THREAD

**Issue by tmheath** [hyprwm/hyprland-wiki#320]
There is a Slackbuild for this enabling easy install into Slackware which is not mentioned in the wiki.
This likely should more be a discussion but didn't see the tab for it. Should the wiki include it as an
unsupported installation method?

**Comment by tmheath** [comment]
https://slackbuilds.org/repository/15.0/desktop/hyprland-bin/?search=hyprland
https://wiki.hyprland.org/Getting-Started/Installation/
References

**Comment by vaxerski** [comment]
idk

**Comment by foopsss** [comment]
Fork the repo and add the instructions for Slackware. You can then send a merge request to vaxerski to get them added here.

**Comment by tmheath** [comment]
Will do... thanks...
Probably not tonight, if not tomorrow probably by the start of the next week, going ahead and forking now though.

**Comment by tmheath** [comment]
https://github.com/hyprwm/hyprland-wiki/pull/321
The pull request is ready for review already
