### ISSUE TITLE
Spotify follows window rules now

### ISSUE THREAD

**Issue by shasherazi** [hyprwm/hyprland-wiki#322]
The following lines

https://github.com/hyprwm/hyprland-wiki/blob/b8de59bf08eec5f1d8103e16744b749ff4315b93/pages/Useful%20Utilities/App-Clients.md?plain=1#L16-L17

used to be true, but I have recently noticed that Spotify does follow window rules. For example, now it opens in its designated workspace. This is due to some recent update because I remember it not respecting the window rules.

**Comment by vaxerski** [comment]
patches welcome

**Comment by shasherazi** [comment]
Closed by #323
