### ISSUE TITLE
Update "Status Bar" chapter for Waybar: replace 'wlr/*' with 'hyprland/*'

### ISSUE THREAD

**Issue by akdevservices** [hyprwm/hyprland-wiki#326]
Update "Status Bar" chapter for Waybar: replace 'wlr/*' with 'hyprland/*' for ver. 0.29.1

**Comment by vaxerski** [comment]
https://github.com/hyprwm/hyprland-wiki/pull/327

**Comment by akdevservices** [comment]
> #327

https://wiki.hyprland.org/0.29.1/Useful-Utilities/Status-Bars/

> ### Compiling manually
> ... If you want to use the workspaces module, first, copy the configuration files from /etc/xdg/waybar/ into ~/.config/waybar/. Then, in ~/.config/waybar/config replace all the references to sway/workspaces with wlr/workspaces

> ### Scrolling through workspaces
> ... "wlr/workspaces": {

> ### Clicking on a workspace icon does not work!
> ... On the wlr/workspaces module...
