### ISSUE TITLE
[BUG] Hyprland config 'float' space sensitiv in hyprctl.conf

### ISSUE THREAD

**Issue by 4ctiv** [hyprwm/hyprland-wiki#353]
Problem Description: 
  In the configuration file (*hyprland.conf*) the following (1) will produce config errors, where as (2) does not.
  (2): `windowrulev2 = float ,           class:^(kitty)$,title:^(quickgui)$`
  (1): `windowrulev2 = float,           class:^(kitty)$,title:^(quickgui)$`
  - The float in the first example has a __follwing space__ ` ` __before__ the `,` resulting in the error "*Config error at line ... : Invalid rulev2 found:float \n Hyprland may not work correctly*".

Expected behaviour:
  The configuration in (1) and (2) are logically equivalent and produce the same (no error) behaviour settings in hyprland.
 - NOTE: (3): `windowrulev2 = center         , class:^(kitty)$,title:^(quickgui)$` for example is a valid configuration in *hyprland.conf* 
 
System: 
  [Distro] ArcoLinux , 
  [Kernel] 6.5.4-zen2-1-zen , 
  [CPU] Intel i5-8600K , 
  [GPU] Intel Arc A770 , 
  [MEM] 31.29GiB 
Hyprland related packages:
  arcolinux-hyprland-git              23.08-02
  arcolinux-hyprland-profile-git 23.06-01
  hyprland-dev                              r3232.942ee943-1
  hyprpicker-git                            r35.f6c24d9-1
  xdg-desktop-portal-hyprland 1.1.0-2
  wayland                                      1.22.0-1
  lib32-wayland                            1.22.0-1

**Comment by vaxerski** [comment]
wrong tracker. fixed in https://github.com/hyprwm/Hyprland/commit/352ceb1117b79cd0bc3fa86ebe435b6909512ddb
