### ISSUE TITLE
"colormgr get-devices" shows no output devices for wayland

### ISSUE THREAD

**Issue by st-binder** [hyprwm/hyprland-wiki#354]
I would love using hyprland for work but this requires the installation of color correction profiles. For wayland this should be possible with "colormgr set-device-profile deviceID profileID". But not in hyprland. The command "colormgr get-devices" shows no connected devices or displays.

**Comment by Aqa-Ib** [comment]
You are posting on the hyprland **wiki** issue tracker. Wrong place, you may want to post in the hyprland issue tracker or maybe in the discussions tab.
