### ISSUE TITLE
Any way to use non-mod keys only?

### ISSUE THREAD

**Issue by chloecdn** [hyprwm/hyprland-wiki#358]
I have a very stupid mini-keyboard, not allowing me to rebind keys in any way, so i have to rely 100% on external software to do that. So i currently had my right menu key + f9-f11 bound to my media keys (because fn does not have that functionality).

Is there any way to bind for example menu + f10? because from what ive seen, only specific keys (like super, alt, etc) can be used for that. What i intend is using something like `bind = ,menu ssharp, exec, playerctl play-pause`.

**Comment by chloecdn** [comment]
fucked up and posted on the wrong page lol, my bad ._.

**Comment by Aqa-Ib** [comment]
@chloecdn check this out: https://github.com/rvaiya/keyd

**Comment by chloecdn** [comment]
> @chloecdn check this out: https://github.com/rvaiya/keyd

wow, thanks! tried it out, and it seems to work flawlessly. at least how i set it up. I just did it the dirty easy way, and rebound "menu" to "leftmeta", which... "does the job" lol.
