### ISSUE TITLE
Unnecessary vulkan dependencies for ubuntu

### ISSUE THREAD

**Issue by espro1** [hyprwm/hyprland-wiki#378]
The installation guide for ubuntu (at: http://wiki.hyprland.org/Getting-Started/Installation/#installation) lists a few vulkan dependencies:

`libvulkan-dev libvulkan-volk-dev  vulkan-validationlayers-dev libvkfft-dev libgulkan-dev`

I have consulted The Experts (tm), and they say these are in fact not necessary to compile Hyprland, and suggested I create this issue.

**Comment by vaxerski** [comment]
feel free to mr

And yes vulkan is not used
