### ISSUE TITLE
Archlinux official repo package cannot be built

### ISSUE THREAD

**Issue by WinterStar2** [hyprwm/hyprland-wiki#398]
Hyprland seems to use three different build systems, Cmake, Ninja and Meson at once, in unintended / unexpected ways. Apparently this is one of the factors that causes the package maintainer sufficient issues that the official Arch repo package is now several versions behind.

Are there plans for the multiple build system situation to be resolved at some point? 

(Additionally the hyprland-git package in the AUR seems to not adhere to VCS package guidelines. I'm not sure that that's a thing for here, but just figured it might be of help to mention that as well.)

**Comment by vaxerski** [comment]
source for that? We've been using this system forever and arch was doing just fine. Meson is maintained mostly for nix and systems that need it, CMake is the most official pipeline that I always guarantee to work, and is usually the default.

There is no "issue", as meson (+ninja) and cmake, both build and work just fine

**Comment by WinterStar2** [comment]
About my source:
I had direct contact with the maintainer of the Hyprland package via the official Archlinux IRC channel. 
You could join the IRC channel and verify the above with him directly. Most if not all of the Arch developers are in there as well, as well as several WM or DE developers so it might be useful in general.

**Comment by vaxerski** [comment]
@alerque sorry for messaging here but wrt the arch package:

![image](https://github.com/hyprwm/hyprland-wiki/assets/43317083/8ab669bb-8a64-434d-8c12-efb07f24fe3f)

is wrong, it misses `src/version.h` and thus prevents plugins from compiling correctly on arch. Should be `.h*` like we do in our makefile:

![image](https://github.com/hyprwm/hyprland-wiki/assets/43317083/0906e13a-6be1-47a5-b799-f9c77afd5009)

**Comment by alerque** [comment]
Thanks, I'll fix it. But your version catches in template file too. Try `\( -name '*.h' -o -name '*.hpp' \)` instead. Also packaging bugs are probably best tracked on Arch's packaging bug tracker (each package has one).

If you ever have an interest in untangling the build systems so you aren't using Make as a job runner to call CMake to sort out subprojects that calls Ninja to do actual builds, feel free to tag me in an issue. Any of autotools / cmake / meson could handle this project but daisy chaining them all three together is kind of ridiculous and means we have to re-invent stuff to package it.

**Comment by vaxerski** [comment]
I would migrate to cmake only but @fufexan likes his meson for nix

> But your version catches in template file too.

fair point. That can be fixed.

> Also packaging bugs are probably best tracked on Arch's packaging bug tracker (each package has one).

yeah but I need an account on the gitlab and I don't think I can sign in with github there, at least there is no such option
