### ISSUE TITLE
What means output variable in touchdevice and tablet subcategories?

### ISSUE THREAD

**Issue by Loara** [hyprwm/hyprland-wiki#411]
I've noted in `input:tablet:` and `input:touchdevice:` the following option:

> output : "the output to bind touch devices. Empty means unset and will use the current / autodetected".

but doesn't specify what is effectively a valid output (a monitor name, the "virtual lavout" where monitors lies, ...) and this property is not specified in any other section so it's not possible to infer its meaning. I think the description should be more clear about what could be a valid output.

Moreover, [this answer](https://www.reddit.com/r/hyprland/comments/17olamh/mapping_tablet_to_output_doesnt_work/) says that `touchdevice` section doesn't work anymore, therefore the wiki should be accordingly updated or at least add a warning about a currently experimental feature.

**Comment by Loara** [comment]
Now the description has been updated, I close the issue.

**Comment by carbolymer** [comment]
How do I set this option? 
```
touchdevice {
    output = e-DP1
}
```
This sends input to the active window on any monitor and not to `e-DP1`.
