### ISSUE TITLE
Keyboard compose keys

### ISSUE THREAD

**Issue by SerjeiMikailov** [hyprwm/hyprland-wiki#423]
My keyboard layout is 'us' standard, but i need to type Ç and another special keys, how can i activate the compose keys in Hyprland?  I tried go to '/etc/X11/xorg.conf.d/00-keyboard.conf' and change the 'Option "XkbOptions' to 'compose:rctrl' but not worked.

**Comment by fufexan** [comment]
https://wiki.hyprland.org/Configuring/Variables/#input `input:kb_options` is what you want.
Also, this issue does not belong in this repo.
