### ISSUE TITLE
Can't propose changes to pages that aren't in the repo (old GitHub wiki lefover?)

### ISSUE THREAD

**Issue by wkjagt** [hyprwm/hyprland-wiki#442]
I came to this repo to open a pull request to propose a change to some wording on a particular page I found on the wiki, but then I found that this page isn't even in this repo. After some looking around I found it's (I guess?) a leftover from the old GitHub wiki before it was migrated. 

- [The page in question](https://wiki.hyprland.org/hyprland-wiki/pages/Configuring/Advanced-config/)
- [The same page in the GitHub wiki](https://github.com/hyprwm/Hyprland/wiki/Advanced-config/ed35cebfc2696d7b145c573d5d230cfcd0dad0ee) (an old commit)

I didn't navigate to this page through the Wiki navigation by the way, and it doesn't seem to be part of it. It was a Google search that took me to it. So I guess pages in the old wiki that aren't part of the migrated version are still there. Not even sure this is valuable information, so feel totally free to close this issue if it isn't.

The phrase in question:

> Please use the offset for its intended purpose before asking stupid questions about "fixing" monitors being mirrored.

I felt it didn't fit with the tone of the rest of the wiki so was going to propose a change.

**Comment by vaxerski** [comment]
I think I managed to purge the outdated leftover garbage from the backend. Sorry for that.

**Comment by wkjagt** [comment]
> I think I managed to purge the outdated leftover garbage from the backend. Sorry for that.

Awesome. That same page now returns a 404 👍 Thanks!
