### ISSUE TITLE
New Wiki UI

### ISSUE THREAD

**Issue by Enigma1309** [hyprwm/hyprland-wiki#458]
Hello everyone, I'm thinking of making a new Hyprland Wiki UI with [retype](https://retype.com/)
a lot of other websites use this as a wiki option since it's fast to work with and more flexible than the current one, i

- Aesthetics, the Hyprland thing... 
- It has better search and filtering than current wiki 
- It has faster editing 
- Can be easily built and deployed 
-  Examples :- thewiki.moe, https://champagne.pages.dev/

I'll be building this if anyone is interested in contributing and approving this

**Comment by fufexan** [comment]
> * It has faster editing

Editing speed is entirely up to the user. All you have to do is change the markdown. I don't see how speed will impact the wiki.

> * Aesthetics, the Hyprland thing...

That's entirely up to the theme. We can change the current theme and achieve similar results.

> * It has better search and filtering than current wiki

Again, up to the theme to implement it.

> * Can be easily built and deployed

So can Hugo.

So far I see no reason to switch from Hugo.

**Comment by Enigma1309** [comment]
ok thanks i think it's okay

**Comment by Enigma1309** [comment]
a quick point i want to put

> We can change the current theme and achieve similar results.

if we can change the current theme then why dont we??

say i'm on the Dispacher's page and looking down, why do i have to scroll all the way up to access the links on the left sidebar.
I'm sometimes frustrated with these small technical inconsistencies.
Thanks in advanced

**Comment by fufexan** [comment]
> if we can change the current theme then why dont we??

I'll be working on it soon. I'm thinking of using https://lotusdocs.dev/docs/.

**Comment by Enigma1309** [comment]
> I'm thinking of using https://lotusdocs.dev/docs/.

This looks pretty good 👀 i'll be willing to help if needed

**Comment by fufexan** [comment]
The new theme was rolled out 2 days ago.

**Comment by Enigma1309** [comment]
Thanks it looks awesome ❤️
(and functional too :D)

**Comment by Enigma1309** [comment]
just found out this bug, hope you are aware of it
![image](https://github.com/hyprwm/hyprland-wiki/assets/94917588/c3b9f66c-6816-4142-9d9c-b31700ebf32e)

Links with capital name redirects to old wiki whereas the one's with small to new wiki
ex:- 
- https://wiki.hyprland.org/configuring/keywords/ this will redirect to new wiki, whereas
- https://wiki.hyprland.org/Configuring/Keywords/ this will redirect to old wiki

Since a lot of issues and their solutions are using old wiki url, a lot of people will endup to the old wiki instead of new one

**Comment by fufexan** [comment]
I am aware of this issue, and will try to change back all the links today.
