### ISSUE TITLE
[Feature] Multilingual support

### ISSUE THREAD

**Issue by clsty** [hyprwm/hyprland-wiki#478]
The content on this wiki website is extensive.

Although I can read English, it is still inconvenient to refer to it frequently.

P.S. @fufexan I [saw you said that](https://github.com/hyprwm/hyprland-wiki/issues/458#issuecomment-1935041558) the website might switch to another hugo theme "lotusdocs".

That's great, because "lotusdocs" support multilingual. It also support content searching using CJK characters.

And if you're really supporting multilingual, I'll contribute in zh-CN translation.

**Comment by vaxerski** [comment]
that's not a good idea. Translations will get dangerously out-of-sync.

**Comment by clsty** [comment]
> that's not a good idea. Translations will get dangerously out-of-sync.

True, it makes sense.

But, take Arch Wiki as example, it has multilingual support, and on the top of the translated page there is a notice about the last time this page is updated, and also a link to the original language.

If we could implement such warning/notification, will you feel it better?

**Comment by vaxerski** [comment]
we can't, I believe.

Besides, the speed at which arch wikis get out of date is _far_ slower than hyprland. We've had like at least 3 breaking changes in your config alone since latest release 0.35 like 2-3 weeks ago.

**Comment by clsty** [comment]
> Besides, the speed at which arch wikis get out of date is _far_ slower than hyprland. We've had like at least 3 breaking changes in your config alone since latest release 0.35 like 2-3 weeks ago.

Wow, this speed is so astonishing.

In such case, I hope multilingual could be implemented some other day in future.

Closing for now.
