### ISSUE TITLE
Broken Screen Sharing Link 

### ISSUE THREAD

**Issue by crispy-caesus** [hyprwm/hyprland-wiki#510]
on https://wiki.hyprland.org/Useful-Utilities/Screen-Sharing/ the [amazing gist by PowerBall253](https://gist.github.com/PowerBall253/2dea6ddf6974ba4e5d26c3139ffb7580) seems to have been deleted or moved

**Comment by vaxerski** [comment]
https://github.com/hyprwm/hyprland-wiki/pull/497
