### ISSUE TITLE
Which signal is used for  Dispatch - `killactive`, `closewindow`  and `hyprctl kill`

### ISSUE THREAD

**Issue by KAGEYAM4** [hyprwm/hyprland-wiki#520]
![image](https://github.com/hyprwm/hyprland-wiki/assets/75798544/e815901f-e84a-4a64-94d4-9e485e24dd11)
![image](https://github.com/hyprwm/hyprland-wiki/assets/75798544/7e76ed1b-43d7-425e-9799-cea826a0e163)

Which signals are used for above commands? Is it `SIGKILL`? or `SIGTERM`?

If it is `SIGKILL`? Then how to achieve more graceful kill using `SIGTERM`?

**Comment by vaxerski** [comment]
hyprctl kill does a sigkill, everything else is term
