### ISSUE TITLE
Crash when configuring monitor in config file

### ISSUE THREAD

**Issue by rmarku** [hyprwm/hyprland-wiki#523]
I connected a new monitor to my PC. If I connected it when Hyprland is running, the monitor works great, and I can configure it with `wdisplays`. `wdisplays` changes are applied and everything works great.

Now I want to add a custom `monitor` config for this display. As it is rotated 180, it is a pain to configure it every time with `wdisplay`.

When I add the following simple config, Hyprland crash and did not start any more (always crash)

```
monitor=DP-3,preferred
```

<details><summary>hyprctl monitors output</summary>

```
Monitor eDP-1 (ID 0):
	1920x1080@360.00601 at 3640x300
	description: BOE 0x09B9
	make: BOE
	model: 0x09B9
	serial: 
	active workspace: 2 (2)
	special workspace: 0 ()
	reserved: 0 35 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false

Monitor DP-1 (ID 1):
	2560x1440@59.95100 at 1080x200
	description: HP Inc. HP E273q 6CM94221N8
	make: HP Inc.
	model: HP E273q
	serial: 6CM94221N8
	active workspace: 3 (3)
	special workspace: 0 ()
	reserved: 0 35 0 0
	scale: 1.00
	transform: 0
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false

Monitor DP-3 (ID 2):
	1920x1080@60.00000 at 1393x1640
	description: ASUSTek COMPUTER INC ASUS MB16AC LALMTF127915
	make: ASUSTek COMPUTER INC
	model: ASUS MB16AC
	serial: LALMTF127915
	active workspace: 4 (4)
	special workspace: 0 ()
	reserved: 0 35 0 0
	scale: 1.00
	transform: 2
	focused: yes
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false

Monitor HDMI-A-1 (ID 3):
	1920x1080@60.00000 at 0x0
	description: LG Electronics 23EA53
	make: LG Electronics
	model: 23EA53
	serial: 
	active workspace: 1 (1)
	special workspace: 0 ()
	reserved: 0 35 0 0
	scale: 1.00
	transform: 1
	focused: no
	dpmsStatus: 1
	vrr: 0
	activelyTearing: false
```
</details>

[hyprlandCrashReport1012365.txt](https://github.com/hyprwm/hyprland-wiki/files/14574719/hyprlandCrashReport1012365.txt)

**Comment by rmarku** [comment]
Finally working. It started not crashing with:

```
monitor-DP-3,preferred,auto,1
```

and finally is working correctly as follow

```
monitor=desc:ASUSTek COMPUTER INC ASUS MB16AC LALMTF127915,preferred,1354x1640,1,vrr,1,transform,2.0
```

I will let the issue open, as I think that showing an error would be a better outcome of a bad monitor configuration instead of a crash.

**Comment by vaxerski** [comment]
fixed
