### ISSUE TITLE
New wiki theme makes callouts unreadable in light mode

### ISSUE THREAD

**Issue by AngeloThys** [hyprwm/hyprland-wiki#534]
### Browser

Firefox & Chromium

### Extensions

None

## Examples

[Dispatchers: Special workspaces](https://wiki.hyprland.org/configuring/dispatchers/#special-workspace)

![image](https://github.com/hyprwm/hyprland-wiki/assets/91565194/1f8117b3-1af5-428e-b1ca-6bb659e717f0)
![image](https://github.com/hyprwm/hyprland-wiki/assets/91565194/053bf7e5-bd40-4ee5-8bc5-b3438542f1b0)

[Dispatchers: Executing with rules](https://wiki.hyprland.org/configuring/dispatchers/#executing-with-rules)

![image](https://github.com/hyprwm/hyprland-wiki/assets/91565194/aef2811d-cecf-4c70-ade4-60b9f50107a5)
![image](https://github.com/hyprwm/hyprland-wiki/assets/91565194/ade1641f-2a89-4265-8a55-8d8babe122e7)

**Comment by AngeloThys** [comment]
Related to pull-request #533

**Comment by fufexan** [comment]
No, I'll fix the syntax colors.

**Comment by fufexan** [comment]
@AngeloThys It should be fixed.

**Comment by AngeloThys** [comment]
@fufexan Nice work, I see you made the dark theme more legible as well. 💯
