### ISSUE TITLE
Link in Master tutorial leads to 404

### ISSUE THREAD

**Issue by tuxpengu** [hyprwm/hyprland-wiki#536]
If you go to the "Fully configure" section in the Master tutorial and click on the "Configuring Hyprland page" link, you will be redirected to a 404. This is because the page leads to "https://wiki.hyprland.org/configuring/configuring-Hyprland", and it should be directing to "https://wiki.hyprland.org/configuring/configuring-hyprland". Fix it **now**, faggots.

**Comment by vaxerski** [comment]
@fufexan
