### ISSUE TITLE
default fullscreen mode

### ISSUE THREAD

**Issue by matthis-k** [hyprwm/hyprland-wiki#54]
I use `rofi-lbonn-wayland-git` as application launcher with the fullscreen flag, but i can not get it to cover my status bar (`waybar-hyprland-git`)

Therefore my suggestion to be able to configure the default fullscreen mode, because I want `0` not `1` as the default.

**Comment by vaxerski** [comment]
if it does that it means it either:
a) changes its size and not requests fullscreen
b) requests a maximize and not a fullscreen

both cases are the app's fault.
