### ISSUE TITLE
Multi GPU set up can cause breakages due to dynamic path assignment of GPU

### ISSUE THREAD

**Issue by kiecla** [hyprwm/hyprland-wiki#551]
This issue is about this page:
https://wiki.hyprland.org/Configuring/Multi-GPU/
https://github.com/hyprwm/hyprland-wiki/blob/main/pages/Configuring/Multi-GPU.md

Which was put together in this PR:
https://github.com/hyprwm/hyprland-wiki/pull/267

The issue is that the page advises setting WLR_DRM_DEVICE to /dev/dri/cardN when there is an NVIDIA card present that must be avoided, but the N in that path is assigned dynamically, so in a multi GPU laptop it does not always point to the correct GPU (the non-NVIDIA iGPU.)
It would be better to point to the 'pci-0000:06:00.0-card' device, but wlroots interprets the colon character as a separator, so this is not possible. Using quotation marks does not help here, nor do backslashes or other escaping characters.

There are two solutions that do work:
The first is that wlroots will set WLR_DRM_DEVICE to vga_boot, which should be the iGPU, making the setting of this variable redundant.
(citation: https://github.com/swaywm/wlroots/issues/1386#issuecomment-775043709)
I did have a quick look at the wlroots docs to try to confirm this, and I couldn't there, but I can confirm it 'works on my machine™' and emersion is one of the lead contributors on wlroots so I take his word here as a good citation.
Alternatively, if I am wrong about the first solution, and WLR_DRM_DEVICE must be set, it should instead be set by creating a symlink to the unchanging path to the device, and then using that symlink in hyprland.conf. This bypasses the colon separator issue without putting yourself at risk of the dynamic name assignment of cardN.

I would like to hear some other thoughts on this, like whether anyone else has encountered this issue, or even better if anyone else has fixed this issue by removing the WLR_DRM_DEVICE setting from their hyprland.conf, as I have. If that is the case we'll want a pull request for the multi-GPU page, which I am (tentatively, time allowing) offering to do.

**Comment by vaxerski** [comment]
@fufexan 

also feel free to make a MR to the wiki.

**Comment by fufexan** [comment]
We could mention both solutions, and the user can pick one that suits their needs. I assume there might be people who wish to run Hyprland on their primary GPU, so they will pick the second option.

**Comment by kiecla** [comment]
Pull request accepted and wiki updated with the information discussed. Closing.
