### ISSUE TITLE
Swapping modifier keys

### ISSUE THREAD

**Issue by 2Senn** [hyprwm/hyprland-wiki#554]
Hey guys, thanks for the great docs. I just had a bit of difficulty figuring out if it is possible to swap my left alt and left shift keys? is there a way to do that in kb_options?

**Comment by poetex** [comment]
I believe the [Uncommon Tips & Tricks](https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/#swap-caps-lock-and-escape) page already addresses how to accomplish this behavior. The example provided shows how to swap `caps lock` and `escape` for a given keyboard layout, but this could likely be modified for your use case as well.

Could a project maintainer confirm if this is accurate and close this issue if true?
@fufexan @vaxerski

**Comment by vaxerski** [comment]
looks like it.
