### ISSUE TITLE
 Request to Submit Chinese Translation Documentation

### ISSUE THREAD

**Issue by LoongArum** [hyprwm/hyprland-wiki#560]
### Description:
I am ar0m(JinDongJie), and I am a big fan of the Hyprland project. I would like to help more Chinese users to better utilize this desktop manager. I plan to contribute by translating the project documentation into Chinese and am willing to dedicate my time and skills to complete this task.

### Plan and Approach:

1. I will translate the original project documentation into Chinese step by step, ensuring accuracy and fluency in the translation.
2. I will create a new branch(or a better way) to submit the translated documentation and will maintain regular updates to keep it synchronized.
3. I will collaborate with the community and maintainers to ensure the quality and accuracy of the translated documentation.
4. I hope that this translated documentation will help more Chinese users to easily utilize the Hyprland project.

### Inquiries:
   I have reviewed the current documentation website, and it seems that there is no language switch feature available. In the future, would it be possible to implement a language selection feature within the project? This feature could allow users to choose their preferred language for the documentation, enhancing accessibility for a wider audience.

### Additional Information:
  If you believe that this translation work is valuable and approve of my contribution, I am eager to contribute to the project. I look forward to working with you to make the Hyprland project more user-friendly and inclusive.
  I have used the translation website [weblate.org](https://weblate.org) to translate some other open-source projects that I like. I believe I am capable of handling this task.

Thank you for your time and attention!

**Comment by fufexan** [comment]
Referencing a past issue https://github.com/hyprwm/hyprland-wiki/issues/478.

> In the future, would it be possible to implement a language selection feature within the project?

I believe it can be implemented simply as `https://wiki.hyprland.org/<lang>/`, with a selector in the navbar.

**Comment by LoongArum** [comment]
I'm really excited to hear this news! Should I fork this repository and start translating? Or do you have any better suggestions? I'm eager to start contributing. Perhaps, once Hyprland is  more stable, you could consider releasing these documents. @fufexan

**Comment by fufexan** [comment]
We should check in with Vaxry first, as he was against the previous translation attempt.

**Comment by vaxerski** [comment]
I am against as with last time
