### ISSUE TITLE
Link rot on Uncommon tips & tricks

### ISSUE THREAD

**Issue by 13x1** [hyprwm/hyprland-wiki#566]
The preview GIFs on https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/ are expired Discord links. Those should probably not be hosted on Discord.

FYI, you can still access them by sending the expired link to yourself on Discord to retrieve a new access token. Here are working links (will expire soon too though):

https://cdn.discordapp.com/attachments/810799100940255260/1032843745864986644/ezgif.com-gif-maker18.gif?ex=66189d32&is=66062832&hm=d7d38b4967779b6a96c1f065d605453a0326719277b087cedac744a6564bf6fd&

https://media.discordapp.net/attachments/810799100940255260/1032846469855727656/ezgif.com-gif-maker19.gif?ex=66189fbb&is=66062abb&hm=0e702d919b8e8c4df19e5e70fea918b345989937cd3a460cc5db816e72141d51&

**Comment by fufexan** [comment]
Should be fixed by https://github.com/hyprwm/hyprland-wiki/commit/036195c550c18c91d997f85fb917bbcc0ae28f03.
