### ISSUE TITLE
Unhandled python OSError

### ISSUE THREAD

**Issue by Tarch1** [hyprwm/hyprland-wiki#57]
Hi,
I'm using Artix and I would like to install it, but I have this error;
OSError: [Errno 8] Exec format error: '/usr/bin/glslangValidator'

ERROR: Unhandled python OSError. This is probably not a Meson bug, but an issue with your build environment.
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.

PS: I've installed all dependancies

Regards

**Comment by vaxerski** [comment]
wrong repo...?

**Comment by Tarch1** [comment]
ooohps sorry didn't noticed ;(
