### ISSUE TITLE
Hyprlock no clear shortcut docs

### ISSUE THREAD

**Issue by max-ishere** [hyprwm/hyprland-wiki#579]
[Hyprlock page](https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/) doesn't document password clear shortcuts such as:

[Source code](https://github.com/hyprwm/hyprlock/blob/bbbb960e42c6738c5f3829da8524835ed68e6400/src/core/hyprlock.cpp#L809)
- <kbd>Esc</kbd>
- <kbd>Ctrl</kbd> + <kbd>U</kbd>
- <kbd>Ctrl</kbd> + <kbd>Backspace</kbd>

Related issue: https://github.com/hyprwm/hyprlock/issues/252

**Comment by vaxerski** [comment]
MRs welcome
