### ISSUE TITLE
Plugins page empty

### ISSUE THREAD

**Issue by crispy-caesus** [hyprwm/hyprland-wiki#616]
https://wiki.hyprland.org/Plugins/ 
![image](https://github.com/hyprwm/hyprland-wiki/assets/114518720/bb24c6bd-198a-40dc-9d65-c6b84a2b1322)

**Comment by vaxerski** [comment]
correct, previous theme's remnants. There is nothing there, but there is content in the subcategories

**Comment by poetex** [comment]
Appears that this issue may have been resolved by e76985b in #748 

It's not necessarily a built out page, but it does include links to the relevant subcategories. 

This issue may be resolved by #748 - I will defer to @fufexan

**Comment by fufexan** [comment]
Right, I forgot about this issue.
