### ISSUE TITLE
missing dependency (hyprwayland-scanner)

### ISSUE THREAD

**Issue by ghost** [hyprwm/hyprland-wiki#624]
### Hyprland Version

.

### Bug or Regression?

Bug

### Description

**https://wiki.hyprland.org/Getting-Started/Installation/**
in this section, in the arch dependencies, the 'hyprwayland-scanner' package is missing.
i tried to manually build hyprland, and i had an error which indicated me that that package is missing.
i'm sorry for my bad english.

### How to reproduce

try to manually build hyprland.

**Comment by vaxerski** [comment]
the problem is that most distros dont have hyprwayland-scanner in their repos yet

**Comment by Ciel-MC** [comment]
> the problem is that most distros dont have hyprwayland-scanner in their repos yet

I installed hyprwayland-scanner from source as well and it didn't pick up on the package either, but when I installed the -git from the aur, it worked, any idea why that is the case? Or is that to be expected because it didn't register in the libraries and whatnot?

**Comment by vaxerski** [comment]
likely because you didnt read the readme and add this part to the cmake command 
![image](https://github.com/hyprwm/hyprland-wiki/assets/43317083/7b0a498e-32e8-4b50-b21d-a2841959fa70)

**Comment by Ciel-MC** [comment]
> likely because you didnt read the readme and add this part to the cmake command ![image](https://private-user-images.githubusercontent.com/43317083/327943989-7b0a498e-32e8-4b50-b21d-a2841959fa70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjE2MzgsIm5iZiI6MTcxNDgyMTMzOCwicGF0aCI6Ii80MzMxNzA4My8zMjc5NDM5ODktN2IwYTQ5OGUtMzJlOC00YjUwLWIyMWQtYTI4NDE5NTlmYTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDExMTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YjVkZDM4NTBiYTY2NzNiNWMxNDI0YTY0NTRhNjM4MjI5YjhlM2Y4ZmIxZGE3ODE1MjBjYjJjYzgxZGQzZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KbGfxsncK2mnfbXuFV-EzjmAoYGa9-OPAblAoNYJNmE)

It was there, I copied from the repo into the script. I did figure it out though, the syntax used in the readme does not behave the same `fish` which I use, not sure why I didn't notice that later as I did notice it on other projects and one time even remove it, but it still didn't work. Regardless, now that I fixed the syntax, it is now working fine. Oops

**Comment by leon-erd** [comment]
Can be closed right?

**Comment by vaxerski** [comment]
yea
