### ISSUE TITLE
IPC page lists incorrect socket path

### ISSUE THREAD

**Issue by spinningvenus** [hyprwm/hyprland-wiki#629]
[The page documenting IPC](https://wiki.hyprland.org/IPC/) lists the two available sockets under the path **$XDG_RUNTIME_DIR/hypr/[HIS]/.socket.sock**, however on the latest version of Arch the correct path is **/tmp/hypr/[HIS]/.socket.sock**. 

After confirmation that this is a mistake and not an issue unique to my system, I'll submit a pull request to update the path.

**Comment by vaxerski** [comment]
yea I forgor

**Comment by spinningvenus** [comment]
cbd4f319717e6b38cae3d500d2be2f0bdeb4a6dc
