### ISSUE TITLE
Doubts on `#Bisecting an issue`

### ISSUE THREAD

**Issue by KAGEYAM4** [hyprwm/hyprland-wiki#638]
The step -> `sudo make install` is confusing, would it ovrewrite the hyprland-package of my system? 

Looking at Makefile in hyprland repo, it contains  -> `PREFIX = /usr/local`

So it will be installing it in `/usr/local` subdirectories? If yes, would be alright to update the documentaion on that user should run the Hyprland from `/usr/local/bin/Hyprland`?

**Comment by davc0n** [comment]
@vaxerski @KAGEYAM4 can be closed imho
