### ISSUE TITLE
IPC Example still uses tmp directory for socket2

### ISSUE THREAD

**Issue by Pummelfisch** [hyprwm/hyprland-wiki#644]
The example for socket2 on the IPC Wiki page (https://wiki.hyprland.org/IPC/#how-to-use-socket2-with-bash) at the bottom, still uses the

```
/tmp/hypr/…
```

directory. With v0.4 this has moved to `$XDG_RUNTIME_DIR`

So an updated example would look like this:

```
#!/bin/sh

handle() {
  case $1 in
    monitoradded*) do_something ;;
    focusedmon*) do_something_else ;;
  esac
}

socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
```

**Comment by vaxerski** [comment]
c56516109eea6dabd64d99c03ae4b0869a2612d4
