### ISSUE TITLE
When does this update live wiki.hyprland.org?

### ISSUE THREAD

**Issue by Benzolio** [hyprwm/hyprland-wiki#663]
I just went around in some circles trying to figure out why my config broke with an error the no_cursor_warps does not exist, although the wiki shows (out of date) variables in the general section, and has no cursor section. I figured it out from looking at recent commits that general:no_cursor_warps has been migrated to cursor:no_warps and came here to make a contribution, but I see this repo has already been updated with the new cursor config variables.
However, the live wiki is still showing old content. I figured I should bring this up just in case something has interrupted the process of updating the wiki.

**Comment by fufexan** [comment]
The section is there https://wiki.hyprland.org/Configuring/Variables/#cursor. Maybe clear the cache/force reload the wiki (Ctrl-Shift-R).

**Comment by vaxerski** [comment]
updates every 1-2 minutes depending on the backend timings, unless the secondary backend's updater dies (it sometimes does) then until I restart it

**Comment by Benzolio** [comment]
@fufexan I see I was looking at the Basic Configuration section, which references some old variables related to cursor.

@vaxerski Thanks, Vaxry! I see it was not the issue of the wiki not updating from the repo. I was looking at a section that is not yet updated here.

**Comment by vaxerski** [comment]
basic configuration? that page doesnt exist.

**Comment by Benzolio** [comment]
Although... Maybe https://wiki.hyprland.org/Configuring/Basic-Config/ is not supposed to be visible anymore? Or redirected to https://wiki.hyprland.org/Configuring/Configuring-Hyprland/?

**Comment by Benzolio** [comment]
> basic configuration? that page doesnt exist.

Ah, yeah. You replied while I was still checking to see if the page is still served. And it appears the old Basic Config page is still live.

**Comment by vaxerski** [comment]
ugh, I thought I nuked it but it keeps coming back
