### ISSUE TITLE
GPU configuration with "env = WLR_DRM_DEVICES,/dev/dri/cardN" not working as expected?

### ISSUE THREAD

**Issue by ssvx** [hyprwm/hyprland-wiki#694]
In reference to https://wiki.hyprland.org/hyprland-wiki/pages/Configuring/Multi-GPU/

My cards from `lspci | grep -E 'VGA|3D'` are
- 17:00.0 VGA compatible controller: NVIDIA Corporation GA102 [GeForce RTX 3090] (rev a1)
- 67:00.0 VGA compatible controller: Intel Corporation DG2 [Arc A770] (rev 08)

And from `ls -l /dev/dri/by-path` i get `pci-0000:67:00.0-card -> ../card0`, so i've set `env = WLR_DRM_DEVICES,/dev/dri/card0` in my hyprland.conf, which should refer to my A770.

But even when i unload all nvidia kernel mods with `sudo rmmod nvidia_drm nvidia_modeset nvidia_uvm nvidia` before running `Hyprland` it seems to automatically load at least the nvidia driver and also seems to be running on that:

`lsof -n -w -t /dev/nvidia*`
> 5771

`ps -p 5771`
>    PID TTY          TIME CMD
>   5771 tty1     00:00:45 Hyprland

Also when running kitty, Xwayland or chrome-based browser (Vivaldi) they all seem to jump onto the nvidia train.

Problem is that i want to attach/detach my 2nd GPU (nvidia) to be used on demand either as 3d accelerator for certain apps/games in Hyprland natively and wine **or** use the vfio drivers to pass the card on to qemu/kvm and use it as dedicated GPU for a virtual machine.

I've been told i'd need to blacklist nvidia drivers and reboot to use the GPU with vfio and then remove it from the blacklist and reboot again in order to use it within the host machine again. I find this very strange and cumbersome and would much prefer the GPU not being used as long as i configure Hyprland to use a different GPU and don't explicitly tell anything to load my nvidia kernel mods..?

Also: is there a way to check which GPU Hyprland thinks it's using to confirm the `env = WLR_DRM_DEVICES,/dev/dri/card0` does anything at all?

**Comment by izmyname** [comment]
I suggest closing as there is no more 'WLR_DRM_DEVICES' variable in Hyprland.

**Comment by benekreng** [comment]
Have you solved the issue?

**Comment by ssvx** [comment]
> Have you solved the issue?

There was another comment (no idea where it went) by @izmyname which suggested to close the issue "as there is no more 'WLR_DRM_DEVICES' variable in Hyprland" - so i guess the issue in general lost its target :sweat_smile:

**Comment by l0f3n** [comment]
Having almost the same issue as you. Any update? Any other issues/threads I can follow?

**Comment by ssvx** [comment]
> Having almost the same issue as you. Any update? Any other issues/threads I can follow?

Err... noticed i posted on hyprwm/hyprland-wiki (brain's not braining) and assuming the wiki is correct, this is an issue with Hyprland..? So i just threw this one out to hyprwm/Hyprland: https://github.com/hyprwm/Hyprland/issues/8679

You're welcome to contribute there and make me look less mental by admitting you can't get it working either :sweat_smile:

**Comment by Guru-Gopireddy** [comment]
Yo bro, I have (almost) the exact same issue as you. I have a laptop with integrated AMD and dedicated Nvidia graphics. Hyprland always uses Nvidia graphics unless I boot into windows and power-gate Nvidia graphics using ghelper, and only then is hyprland forced to use integrated graphics. I haven't found a fix yet, unfortunately
