### ISSUE TITLE
Version selector broken

### ISSUE THREAD

**Issue by saygo-png** [hyprwm/hyprland-wiki#701]
To replicate:
- go to https://wiki.hyprland.org/version-selector/
- pick one of these versions v0.41.2,  v0.41.1,  v0.41.0
- click on any item on the left sidebar, such as "Keywords"
- your version is now back to latest git.

This only seems to happen with those 3 versions so far.

**Comment by Atemo-C** [comment]
I can reproduce the issue.

https://github.com/hyprwm/hyprland-wiki/assets/160250128/af064a14-8667-4d00-b1c3-ced8e77626b6

**Comment by vaxerski** [comment]
is the page content actually git?

**Comment by Atemo-C** [comment]
I can confirm it is actually git. The easiest way for me to check was to see if [this](https://github.com/hyprwm/hyprland-wiki/commit/1e1848b6844ccd8154e0d49ac3e70f97e99240ab) was here or not.
- In latest (git), it is here.
- In 0.41.2, it is not.
- When in 0.41.2 and re-clicking on "Master tutorial", it does go back to git.

Manually adding the version number into the URL seems to fix the issue...until you click on another link.

**Comment by vaxerski** [comment]
likely I exported it wrong, let me fix that.

**Comment by vaxerski** [comment]
yeah. Sorry, I do it manually and forgot to fix the URL. 0.41.2 is fixed. I'll fix 0.41.0 in a sec

**Comment by vaxerski** [comment]
0.41.0(1) fixed too
