### ISSUE TITLE
Make Sidebar index follows (scroll to) the current visible page

### ISSUE THREAD

**Issue by YahiaJr** [hyprwm/hyprland-wiki#765]
When viewing a section in the wiki that's in the lower section in the index, it doesn't appear by default in the sidebar.

for example, when viewing the nix-related instructions, every time I need to go to another page (not the next one necessarily) in the nix section I have to scroll down to be able to see the rest of the section's pages.
![image](https://github.com/user-attachments/assets/06b26016-61fd-437e-9a50-70f22f8d0a03)

it's not much of an issue, but it's inconvenient UX.

**Comment by fufexan** [comment]
I'm aware of this, and have raised an issue a while ago https://github.com/imfing/hextra/issues/395.

**Comment by fufexan** [comment]
Updated the theme yesterday, and the behaviour is present.
