### ISSUE TITLE
Nix page should mention kitty as a requirement

### ISSUE THREAD

**Issue by Kyesarri** [hyprwm/hyprland-wiki#766]
Page: https://wiki.hyprland.org/Nix/

Recent thread on Reddit, a user was having issues with Hyprland hanging not responding to inputs (super + m)

The result of the thread was the user did not have kitty installed and was causing Hyprland to hang / become non responsive.

Perhaps editing the first code block on that page to read:

```
{
  programs = {
    kitty.enable = true; # requirement for the default hyprland config
    hyprland.enable = true; # enable hyprland
  };
  # Optional, hint electron apps to use wayland:
  # environment.sessionVariables.NIXOS_OZONE_WL = "1";
}
```
Would avoid similar threads from newcomers. I can fork and raise a PR if required.

**Comment by fufexan** [comment]
Thanks, added in a840855.
