### ISSUE TITLE
Using plugins from Nixpkgs needs updating/clarification

### ISSUE THREAD

**Issue by Kommynct** [hyprwm/hyprland-wiki#773]
If I put
```
  wayland.windowManager.hyprland.plugins = [
    pkgs.hyprlandPlugins.hyprexpo
  ];
```

into my configuration.nix, for example, I get

"The option `wayland' does not exist."

This section really needs clarification, i'm assuming this is a section where you can use nixpkgs without home manager or the nix flakes

**Comment by vaxerski** [comment]
@fufexan

**Comment by fufexan** [comment]
My bad, I forgot to mention that option is only available using Home Manager. I will update that in a bit.

**Comment by fufexan** [comment]
Fixed in 5a2bc45.

**Comment by Kommynct** [comment]
One more small thing, is there no way to install plugins without home assistant?

**Comment by fufexan** [comment]
You can include them the regular way using `plugin = /path/to/libplugin.so` in your configuration directly. You can also use `hyprctl plugin load /path/to/libplugin.so`.

**Comment by Kommynct** [comment]
But if installed from nixpkgs isn't there not a path like that? Sorry I'm very new to nixos

**Comment by fufexan** [comment]
No. Might be possible to add, but I haven't had time for it yet.
