### ISSUE TITLE
`programs.kitty` does not exist, inaccuracy in `Hyprland on NixOS.md`?

### ISSUE THREAD

**Issue by valentinegb** [hyprwm/hyprland-wiki#778]
I'm new to Nix and NixOS, so please forgive me if I am misunderstanding, but it seems to me that `programs.kitty` is not an option that exists despite it being mentioned as such in `Hyprland on NixOS.md`:

https://github.com/hyprwm/hyprland-wiki/blob/48693c72e47afd86db4abe4c79faaa0ce836722b/pages/Nix/Hyprland%20on%20NixOS.md?plain=1#L37-L38

Searching for options containing `kitty` on https://search.nixos.org/options yields no option named `programs.kitty`:

![Screenshot 2024-09-14 at 9 17 45 PM](https://github.com/user-attachments/assets/4728490d-29de-4d7a-9738-b0d472f18315)

**Comment by fufexan** [comment]
My mistake, I'll fix that. In the meantime, you can use this instead
```nix
environment.systemPackages = [
  pkgs.kitty
];
```

**Comment by fufexan** [comment]
Fixed this a while back, forgot to close.
