### ISSUE TITLE
Window dancing trick no longer available.

### ISSUE THREAD

**Issue by qbojj** [hyprwm/hyprland-wiki#785]
https://wiki.hyprland.org/FAQ/#how-to-fix-games-with-window-dancing forwards to https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/#window-dancing, but the window-dancing part is no longer available.

Additionally, I cannot find any info about (removed?) windowrule windowdancing? Why is it no longer supported and what are the alternatives?

**Comment by vaxerski** [comment]
yep it's been removed, I'll yeet the faq entry

> what are the alternatives

There are no alternatives

> Why is it no longer supported

It wasn't maintained properly and was broken. IIRC follow_focus 0 should deal with them
