### ISSUE TITLE
Formatting issue in Ubuntu section of Installation

### ISSUE THREAD

**Issue by pinapelz** [hyprwm/hyprland-wiki#802]
In the [packages](https://wiki.hyprland.org/Getting-Started/Installation/#packages) section of installation. There is some funky formatting issue happening under the Ubuntu details. 
![image](https://github.com/user-attachments/assets/50a9910e-5900-46ae-8aa6-b1204ff28cac)

**Comment by vaxerski** [comment]
yeah idk why the theme broke I guess, maybe we shouldnt nest so much

**Comment by vaxerski** [comment]
@fufexan can you look into this? just undo some formatting I guess until it works

**Comment by fufexan** [comment]
Should be fixed.

**Comment by vaxerski** [comment]
doesnt look like it is
