### ISSUE TITLE
HTML formatting error in docs

### ISSUE THREAD

**Issue by lazlo7** [hyprwm/hyprland-wiki#804]
Installation for ubuntu part has invalid html formatting, there's a seemingly random \<code\> tag displaying literal "\</div\> " inside of it.
https://wiki.hyprland.org/Getting-Started/Installation/#packages

**Comment by vaxerski** [comment]
@fufexan

**Comment by fufexan** [comment]
Should be fixed this time.

**Comment by vaxerski** [comment]
yep, nice work
