### ISSUE TITLE
Missing information about issue with keybind for french keyboard layout (and maybe other ?)

### ISSUE THREAD

**Issue by Wateir** [hyprwm/hyprland-wiki#810]
On hyprland the keybind for go on the workspace 1 is `bind = $mainMod, 1, workspace,  1`  by default

for achive a 1 on a french keyboard layout, you have to make SHIFT + [the same touch as 1 on a qwerty]
if not the touch is & for 1, é for2 and ....

So to go on the workspace 1, it's logic to bind `bind = $mainMod, &, workspace, 1` but this don't work

For this work you have to bind `bind = $mainMod, ampersand, workspace, 1` this is not obvious, so i think it can be cool if it's precise on the wiki

I use https://rherault.dev/articles/hyprland-fr-layout this page of blog to help me fix the issue

**Comment by vaxerski** [comment]
MRs welcome. Generally we do have the note that if you can't find it, you can use `wev`.
