### ISSUE TITLE
Desktop portal page is duplicated

### ISSUE THREAD

**Issue by matejdro** [hyprwm/hyprland-wiki#820]
There seem to be two mostly identical pages for the desktop portal:

https://wiki.hyprland.org/Useful-Utilities/xdg-desktop-portal-hyprland/

https://wiki.hyprland.org/Hypr-Ecosystem/xdg-desktop-portal-hyprland/#configuration

latter seem to contain more information (extra configuration section). Should these two be consolidated?

**Comment by vaxerski** [comment]
ye it was an old deleted page, removed
