### ISSUE TITLE
Configuring/Variables xray Description Error

### ISSUE THREAD

**Issue by poetex** [hyprwm/hyprland-wiki#838]
The `xray` description currently states:

> if enabled, floating windows will ignore tiled windows in their blur. Only available if blur_new_optimizations is true. Will reduce overhead on floating blur significantly.

The variable `blur_new_optimizations` should actually read `new_optimizations`, as `blur_new_optimizations` does _not_ exist as a blur variable.

Consider changing [Line 139](https://github.com/hyprwm/hyprland-wiki/blob/main/pages/Configuring/Variables.md?plain=1#L139) to:

> if enabled, floating windows will ignore tiled windows in their blur. Only available if new_optimizations is true. Will reduce overhead on floating blur significantly.

**Comment by fufexan** [comment]
PRs welcome.
