### ISSUE TITLE
Outdated (duplicated) wiki pages

### ISSUE THREAD

**Issue by PtaxLaine** [hyprwm/hyprland-wiki#891]
Is there any reason for there to be two versions of some wiki pages?

* https://wiki.hyprland.org/configuring/variables/#decoration
* https://wiki.hyprland.org/Configuring/Variables/#decoration

I found the first one using google and was pretty *surprised* when realized it was outdated.

**Comment by fufexan** [comment]
Remnant of a Hugo misconfiguration which did not capitalize URL paths. @vaxerski you should remove that.

**Comment by vaxerski** [comment]
I fucking pruned old pages like just a month ago wtf guys

**Comment by vaxerski** [comment]
fixed
