### ISSUE TITLE
Wiki not updated for the current release

### ISSUE THREAD

**Issue by msmafra** [hyprwm/hyprland-wiki#905]
For example, allow_dumb_copy still in the wiki instead of user_cpu_buffer.

![image](https://github.com/user-attachments/assets/a4df9359-30a0-4a37-a536-806890f8d1e2)

![image](https://github.com/user-attachments/assets/13cdf1fe-fd5c-45d1-b8ef-09f8438fa45e)

Also, in the NVIDIA section, shouldn't no_hardware_cursors be set to 2 or 1 in https://wiki.hyprland.org/0.46.0/Nvidia/

![image](https://github.com/user-attachments/assets/8e9aa551-7cf7-4d51-a196-6232852f49d6)

**Comment by fufexan** [comment]
@vaxerski

**Comment by vaxerski** [comment]
it's just me forgetting to change them, no? You could've fixed that yourself fuf.

**Comment by vaxerski** [comment]
oh wait no nvm I think I fucked up the 46 thing

**Comment by vaxerski** [comment]
fixado
