### ISSUE TITLE
Should wiki for minor versions be generated?

### ISSUE THREAD

**Issue by msmafra** [hyprwm/hyprland-wiki#907]
Just another thing related to https://github.com/hyprwm/hyprland-wiki/issues/905, I guess. It also generates for minor versions, like 0.46.1 or 0.45.2, but not all links work. If I go to https://wiki.hyprland.org/0.46.0/Configuring/Variables/ it works, but https://wiki.hyprland.org/0.46.1/Configuring/Variables/ goes to a 404 page.

**Comment by vaxerski** [comment]
Minor versions redirect to major ones. The reason there is a button for 0.46.1 is for people to not be confused, but it just redirects to 0.46.0.

Minor versions do not introduce any changes, only backport fixes.

**Comment by winkelnp** [comment]
Might be important for other Hypr-Ecosystem stuff though, like recently hyprlock v0.6.1 changed how the fingerprint auth messaging works, but by current state of the wiki (although the wiki was edited too) it seems like the configuration just doesn't work until you dig through merge requests.
